### PR TITLE
fix(repo): compatibility with Flutter 3.19

### PR DESCRIPTION
**Pull request by mauriziopinotti**
# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [X] Code changes are tested (add some information if not applicable)

## Description of the pull request

Adds compatibility for Flutter 3.19, see issue https://github.com/GetStream/stream-chat-flutter/issues/1839

### CODE REVIEW

**Review by matthewfx — APPROVED** [review]

**Comment by esarbanis** [comment]
Hi @mauriziopinotti thank you for opening this and keeping a close eye on the releases, please fix the pipeline errors before we can review/merge.

**Comment by mauriziopinotti** [comment]
> Hi @mauriziopinotti thank you for opening this and keeping a close eye on the releases, please fix the pipeline errors before we can review/merge.

hi @esarbanis the commit message is ok now, I am not sure how to re-run the pipeline:

image

image

**Comment by esarbanis** [comment]
@mauriziopinotti I fixed this for you 🙂 it was in the title of the PR itself. I suspect the other breaks are from not updating `flutter_version` in our [pipelines](https://github.com/GetStream/stream-chat-flutter/blob/beta/.github/workflows/stream_flutter_workflow.yml#L6).

**Review by yeasin50 — COMMENTED** [review]
showBottomSheet change is necessary and works 👍

**Comment by matthewfx** [comment]
Any ETA on this one?

**Comment by mauriziopinotti** [comment]
I have fixed all warning and lints but there are still 2 failing tests.

If a maintainer or anyone else wants to spend some time to fix them that would be appreciated, doing this in my spear time will definitely require weeks to come to an end.

**Comment by esarbanis** [comment]
@mauriziopinotti thank you for the effort you put into this PR, I will take it over, but FYI this is not that easy to drive home, as a full regression test is needed and also it just entered my pipeline ... 😓

**Comment by esarbanis** [comment]
FYI #1870 will make the stable version compatible with flutter versions `>= 3.13.0` once this lands on `master` we will release v7.1.0

**Comment by flodaniel** [comment]
> FYI #1870 will make the stable version compatible with flutter versions `>= 3.13.0` once this lands on `master` we will release v7.1.0

7.1.0 is out, can you merge and release this now? :)

**Comment by esarbanis** [comment]
@flodaniel  I will merge 7.1 to 8 and release a new beta. But out of curiosity, why are you using beta and not stable?

**Comment by mauriziopinotti** [comment]
> @flodaniel I will merge 7.1 to 8 and release a new beta. But out of curiosity, why are you using beta and not stable?

In my case I temporarily switched to beta version some months ago because of updated dependencies, namely package_info_plus (stream chat stable had 4.x and I needed 5.x) and file_picker (stream chat had 5.x and I needed 6.x).

Now I'm back on the stable branch, although dependencies are outdated again (file_picker is now at 8.x and it's not supported by stream chat so I'm forcibly overriding it).

**Comment by esarbanis** [comment]
@mauriziopinotti thank you for your feedback, it is much appreciated. We are very careful when updating a dependency, especially a major version, as they usually come with broken changes. So, we tend to add major version updates of our dependencies to our next major version (beta), so that users are properly informed that this might introduce breaking changes.

Having said that, we are constantly in the process to identify dependencies that can be removed, so that we also remove the complexity they bring to our users.

**Comment by mauriziopinotti** [comment]
> @mauriziopinotti thank you for your feedback, it is much appreciated. We are very careful when updating a dependency, especially a major version, as they usually come with broken changes. So, we tend to add major version updates of our dependencies to our next major version (beta), so that users are properly informed that this might introduce breaking changes.
> 
> Having said that, we are constantly in the process to identify dependencies that can be removed, so that we also remove the complexity they bring to our users.

Yes, this makes perfect sense: and to be honest, I think the "issue" is mostly on the `file_picker` side, since its maintainer bumps the major version often, even if there are no breaking changes and this causes headaches and confusion.

IMHO for you it's a safe choice to be careful about dependencies in the main branch, although maybe that requirement can be loosened in the beta branch.

**Comment by flodaniel** [comment]
> @flodaniel I will merge 7.1 to 8 and release a new beta. But out of curiosity, why are you using beta and not stable?

I was on the beta due to a photo_manager dependency. I was under the impression that 7.1 is not working with flutter 3.19 but that appears to be incorrect so I have now switched to stable 7.1 :)

**Pull request closed without merging**
