### PR TITLE
MessageWidget now has user's name in the timestamp (like advertised design)

### PR DESCRIPTION
**Pull request by nosmirck**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request
Added User's name on the timestamp for the message_widget as advertised on the [website](https://getstream.io/chat/flutter/tutorial/)

Android:
Screenshot_1586272937

iOS:
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-07 at 11 19 40

### CODE REVIEW

**Comment by nosmirck** [comment]
@imtoori I created this little change because I need it and I'm pretty sure more people need it too, also, it needed to match the advertised design

**Comment by imtoori** [comment]
Thanks, I think it's good.
Tomorrow I'll review this pr and modify it to make the name at least optional.

**Comment by nosmirck** [comment]
@imtoori is there any Slack Channel you can invite me so we can coordinate better some changes on the package (like Theme #11 and time separators/grouping #10 ).

I'm implementing chat on our app (I work for Recipe Unlimited) and we need some features that are not yet available and we're glad to help.

**Comment by imtoori** [comment]
I used your email to invite you on a Slack channel, wait for it

**Pull request merged**
