### PR TITLE
fix(ui): Attachment actions on full screen were broken

### PR DESCRIPTION
**Pull request by ayush221b**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

Solves #1071 

The FullScreen implementation and the adjoining widgets had some flaws, because of which we were getting some random unexpected behaviour. I have introduced the concept of StreamAttachmentPackage, that can be used when each individual attachment needs to be mapped to its message, I have also added a new progress UI and changed the way we track download completion for attachments. I have also made the necessary changes to the tests.

### CODE REVIEW

**Comment by ayush221b** [comment]
1. This also removes the `prefer_expression_function_bodies` rule from our analysis options.
2. Also, this exports the file `src/multi_overlay.dart` because that file houses the class `OverlayOptions` which we require when a developer has to pass `customOverlays` to the MessageListView.

**Comment by ibhanu** [comment]
fyi, it brings breaking changes!

**Comment by imtoori** [comment]
@ibhanu that's why it's in v4

**Comment by ibhanu** [comment]
how would it work for backward compatibility?
because old version have this issue.

**Comment by imtoori** [comment]
it doesn't work :( this was the only way to fix it and we pushed it in v4 since it's breaking
I hope that's not a problem, the upgrade is not hard https://getstream.io/chat/docs/sdk/flutter/guides/migration_guide_4_0/

**Pull request merged**
