### PR TITLE
fix: Method being called during build

### PR DESCRIPTION
**Pull request by Nash0x7E2**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)
- [x] Added/Updated documentation where applicable 

### Bug 
As reported:  "When we use ChannelListView and we override the onImageTap trying to push our own view, it throws an error. `onImageTap` is called when the widget is building."

### Fix 
Add lambda which calls `widget.onImageTap` when pressed.

### CODE REVIEW

**Review by imtoori — CHANGES_REQUESTED** [review]
can you fix analysis errors?

**Comment by Nash0x7E2** [comment]
@imtoori I don't think the analysis errors are directly related to this PR. Maybe it's worth opening another PR for that?

**Comment by xsahil03x** [comment]
I agree, let's merge this and create another for the analysis.

**Comment by imtoori** [comment]
yes I changed the branch to develop and I'll merge it
we can fix the analysis later

**Pull request merged**
