### PR TITLE
fix(ui): onThreadTap has been added in MessageWidgetContent to enable thread tap action.

### PR DESCRIPTION
**Pull request by roopak27**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request
onThreadTap has been added in MessageWidgetContent to enable thread tap action.

### CODE REVIEW

**Comment by szechyjs** [comment]
I just ran into this problem today, would love to see this fix!

**Comment by szechyjs** [comment]
@deven98 ping!

**Comment by szechyjs** [comment]
The stale bot is useless, not stale!

**Comment by deven98** [comment]
Hey @roopak27 / @szechyjs apologies some changes are coming for the message widget that must be merged before this is merged. I will keep you posted but I will look at this soon.

**Review by xsahil03x — APPROVED** [review]
LGTM

**Pull request merged**
