### PR TITLE
feat(ui): Extract StreamMediaAttachmentBuilder widget

### PR DESCRIPTION
**Pull request by Mounix99**
# Submit a pull request

Changes requested in [issue](https://github.com/GetStream/stream-chat-flutter/issues/1808#issuecomment-1854057400l)

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

### CODE REVIEW

**Review by kanat — DISMISSED** [review]
LGTM

**Comment by Mounix99** [comment]
@kanat  can you please review it again ?

**Comment by Mounix99** [comment]
Review and everything else takes too long, If someone from package developers can manage this PR by themselves, please do it! Thank you, in advance!

**Review by deven98 — APPROVED** [review]
LGTM

**Pull request merged**
