### PR TITLE
fix: Introduce `showFloatingDateDivider` in `MessageListView` on an older version too

### PR DESCRIPTION
**Pull request by rohan20**
## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [X] Code changes are tested (add some information if not applicable) [There are no tests]
 
## Description of the pull request
- Based on the conversation [here](https://github.com/GetStream/stream-chat-flutter/issues/842#issuecomment-1032767750), my project cannot upgrade to a more recent version of `stream_chat_flutter` due to a cyclic dependencies issue that I haven't fixed yet. We need this change to fix an issue on `stream_chat_flutter: ^2.0.0-nullsafety.2`. 
- I used the change from @imtoori as done [here](https://github.com/GetStream/stream-chat-flutter/commit/eb20b31c825ae430f1cdf367f40fe40e635a5cfc?diff=split) originally.

### CODE REVIEW

**Comment by rohan20** [comment]
@xsahil03x Can you please help me with the failing checks? Are they supposed to pass even for a fix on an old version like this one?

**Comment by xsahil03x** [comment]
Hey @rohan20 , not really needed it's failing due to melos.
This LGTM. Thanks again for the PR 👍🏼

**Comment by xsahil03x** [comment]
Can you also update the version and add a changelog entry for the same? Thanks

**Comment by rohan20** [comment]
Done! Please merge and create a new tag! Thanks for all your help! ⭐

**Review by xsahil03x — APPROVED** [review]
LGTM

**Pull request merged**
