### PR TITLE
fix(llc): add type check in auth_interceptor.dart

### PR DESCRIPTION
**Pull request by xsahil03x**
Fixes: #897

### CODE REVIEW

**Review by HayesGordon — APPROVED** [review]
LGTM

**Comment by mrdemqn** [comment]
Please tell me, when will you release an update with a solution to this problem?

**Comment by xsahil03x** [comment]
Hey @mrdemqn, Probably in the next 2 days.

**Comment by mrdemqn** [comment]
@xsahil03x Thanks a lot

**Pull request merged**
