### PR TITLE
Added onUserAvatarTap

### PR DESCRIPTION
**Pull request by nosmirck**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request
Added onUserAvatarTap for MessageWidget and MessagesListView

### CODE REVIEW

**Comment by imtoori** [comment]
I think it's better to move the GestureDetector in the UserAvatar widget, like the ChannelImage
What do you think?

**Comment by nosmirck** [comment]
> I think it's better to move the GestureDetector in the UserAvatar widget, like the ChannelImage
> What do you think?

Sure, what should I do?

**Comment by imtoori** [comment]
Just move the gesture detector to UserAvatar and add the property also there passing `onUserAvatarTap` to UserAvatar

**Comment by nosmirck** [comment]
@imtoori done!

**Pull request merged**
