### PR TITLE
demo of status change not working

### PR DESCRIPTION
**Pull request by talksik**
An action button in the appbar tries to change a parameter of the local user within `extraData` and it does that successfully. However, for some reason, the updated user received on the stream listener has the updated property online set to false.

Sorry for the noise, I had to add Linux as a platform because that's my development machine. It should be enough to only focus on `example/lib/main.dart` as that's the only place I had changes.

This issue is part of an email conversation I have with Eve from the getstream team. I believe this is a critical bug so hoping this will get resolved soon! :) If you want me to take down this PR, please let me know 👍🏾

### CODE REVIEW

**Comment by talksik** [comment]
Any update on this?

**Comment by esarbanis** [comment]
Hi @talksik ! Thanks for providing this reproduction demo. Can you please switch it to `draft` and provide the link to it from an opened issue? It is a bit hard to track issues if they do not appear in the issue list :pray:

**Comment by talksik** [comment]
@esarbanis Yes sir, I have changed this to draft and created an issue: https://github.com/GetStream/stream-chat-flutter/issues/1810

**Comment by esarbanis** [comment]
Thank you @talksik I appreciate it!

**Comment by deven98** [comment]
Closing this as we've solved the original issue. Thanks for the report and the example!

**Pull request closed without merging**
