### PR TITLE
Fix/send anim duration

### PR DESCRIPTION
**Pull request by deven98**
Added message input theme and send animation duration

### CODE REVIEW

**Review by imtoori — CHANGES_REQUESTED** [review]
LGTM
but I would move some properties that are not in the `MessageInputTheme`, but are related to the `MessageInput`
for example: 
- sendButtonColor
- actionButtonColor
- sendButtonIdleColor
- actionButtonIdleColor
- inputBackground

that are in the `ChannelTheme` as of now

**Comment by xsahil03x** [comment]
Just an opinion but I don't feel `sendAnimationDuration` is something that should be part of the theme. An extra field in the `MessageInput` seems better to me as a `User`.

**Comment by imtoori** [comment]
I get it, but the issue is that it won't be applied to the messageinput while in edit mode

**Comment by deven98** [comment]
Don't we use the message input internally in edit anyway?

**Comment by xsahil03x** [comment]
Yes

**Comment by imtoori** [comment]
yeah that's what I'm saying
if we put it as a param of MessageInput the user will need to customize it in two places, if we put in the theme it will be easier in my opinion
what do you think?

**Review by imtoori — APPROVED** [review]
LGTM

**Pull request merged**
