### PR TITLE
fix(llc): fix channel unread count

### PR DESCRIPTION
**Pull request by imtoori**

### CODE REVIEW

**Review by developerjamiu — COMMENTED** [review]
This does not fix the issue at all. In fact it sets the unread count as zero all the time (after every message).

**Comment by imtoori** [comment]
@developerjamiu can you be more specific?
It fixes the issue, I don't see it when I run the sample app

**Comment by developerjamiu** [comment]
When a new message is sent to a room by a user (whether in the foreground or background), the unreadCountStream keeps returning 0 for the other users.

**Comment by imtoori** [comment]
there are many reasons for that to happen
Are the other users member of the channel?

**Comment by developerjamiu** [comment]
Yes, there are.

**Comment by imtoori** [comment]
I'm quite sure there's an explanation :/ 
Can you try our sample app and see if it works there?
or even this example? https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/example/lib/tutorial_part_4.dart
it's working fine for me, so we need to confirm you're not doing anything wrong

**Comment by developerjamiu** [comment]
Alright, thanks!

**Pull request merged**
